### PR TITLE
Functorize backend.

### PR DESCRIPTION
**Pull request by Tim-ats-d**
- Functorization of the backend so as not to depend on the `configure`. 
- Fail with `"Unsupported platform!"` at runtime if the platform is not supported .

### CODE REVIEW

**Comment by johnelse** [comment]
Hey, thanks for the PR!

Honest question, is there a benefit to choosing the backend at runtime? The backends are OS specific, so we know at compile time which backend is going to work because we know which platform we're compiling for.

I admit the configure script is pretty nasty...I think it would be better to get the generation of `backend.ml` into dune and then do away with the Makefile entirely.

**Comment by Tim-ats-d** [comment]
I have to admit that there is no real advantage except the use of 100% OCaml code :slightly_smiling_face:

The solution to choose backend at compile time in pure OCaml would be to implement a ppx what seems a little too excessive indeed. Actually, I wrote this patch for fun, but maybe someone might be interested?

**Comment by johnelse** [comment]
100% OCaml is an honourable goal indeed :)

It looks like dune is able to copy files (e.g. [here](https://github.com/MinaProtocol/mina/blob/52965c37c1eb37cf071f548e45e1bfd49dca717f/src/config/dune#L26)) and also able to change behaviour depending on which OS it's running on (e.g. [here](https://github.com/ocaml/dune/issues/2310)) - I'll see if I can come up with a solution entirely in dune.

**Comment by johnelse** [comment]
It works! https://github.com/johnelse/spotify-cli/commit/c01937b4be35fb42df58d31d9a5b6ed3d1af66c7

**Comment by Tim-ats-d** [comment]
Nice! So I'm closing this PR, thank you!

**Pull request closed without merging**
